name = "worlds-server"
main = "src/index.js"
compatibility_date = "2023-12-01"

[observability]
enabled = false

[[durable_objects.bindings]]
name = "GAME"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "GameRoom" ]

[[kv_namespaces]]
binding = "USERS"
id = "placeholder-users-kv"
